### ISSUE TITLE
No tests / coverage data

### ISSUE THREAD

**Issue by pkarl** [localytics/kinesis-stream#2]
Tests are a meaningful part of the pitch. I've never written a test for scala (or any scala for that matter), so I don't know how big the ask is here, but the tests may have a transformative effect on the code.

Plus if this is going to be consumed by production, we should have tests.

**Comment by joshcough** [comment]
I have tests, they are running and pass. But, I'm having trouble getting coveralls to work. I just haven't had a chance to look into it. 

It's also worth noting that , while most of the tests are generic and work, they don't actually test against Kinesis. This would require AWS accounts, a kinesis stream to write to, the correct privileges, etc. I might try to set this up in an integration tests directory and have them not run during the normal build. Then hopefully users with sufficient AWS accounts (mostly us, but hopefully others too) could run those tests on their own.

**Comment by joshcough** [comment]
coveralls is now working. only have 11% coverage, but that will get fixed soon. closing this ticket.
